import { dummyPHCs } from '@/dummy/phcs';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { dummyAttendance } from '@/dummy/attendance';
import { dummyMedicines } from '@/dummy/medicines';
import { dummyAlerts } from '@/dummy/alerts';
import { dummyNotifications } from '@/dummy/notifications';
import { dummyReports } from '@/dummy/reports';
import { dummyDistrict } from '@/dummy/district';
import { PHC } from '@/shared/types/phc';
import { AttendanceRecord } from '@/shared/types/attendance';
import { MedicineStock } from '@/shared/types/medicine';
import { AlertItem } from '@/shared/types/alert';
import { NotificationItem } from '@/shared/types/notification';
import { ReportItem } from '@/shared/types/report';
import { AIRecommendation } from '@/shared/types/ai';
import { dummyLogistics, LogisticsRequest } from '@/dummy/logistics';
import { dummyDiseaseTrends, DiseaseTrend } from '@/dummy/diseaseTrends';
import { dummyTasks, TaskItem } from '@/dummy/tasks';

export let localPHCs = JSON.parse(JSON.stringify(dummyPHCs)) as PHC[];
export let localAttendance = JSON.parse(JSON.stringify(dummyAttendance)) as AttendanceRecord[];
export let localMedicines = JSON.parse(JSON.stringify(dummyMedicines)) as MedicineStock[];
export let localAlerts = JSON.parse(JSON.stringify(dummyAlerts)) as AlertItem[];
export let localNotifications = JSON.parse(JSON.stringify(dummyNotifications)) as NotificationItem[];
export let localReports = JSON.parse(JSON.stringify(dummyReports)) as ReportItem[];
export let localDistrict = { ...dummyDistrict };
export let localLogistics = JSON.parse(JSON.stringify(dummyLogistics)) as LogisticsRequest[];
export let localDiseaseTrends = JSON.parse(JSON.stringify(dummyDiseaseTrends)) as DiseaseTrend[];
export let localTasks = JSON.parse(JSON.stringify(dummyTasks)) as TaskItem[];
export let localTelemetryAudits = [
  { id: 'ta-1', type: 'approved', icon: 'check', color: 'emerald', text: 'Redistribution Approved', desc: 'DHO Rajesh Kumar approved transfer of 50 Dengue Kits to PHC Badalpur.', time: '10m ago' },
  { id: 'ta-2', type: 'alert', icon: 'alert-triangle', color: 'red', text: 'Critical Stockout Alert', desc: 'Paracetamol stock dropped below 150 tablets at PHC Badalpur.', time: '1h ago' },
  { id: 'ta-3', type: 'alert', icon: 'activity', color: 'blue', text: 'Disease Trend Spike', desc: 'Malaria cases increased by 15% in PHC Barola.', time: '2h ago' },
  { id: 'ta-4', type: 'approved', icon: 'truck', color: 'orange', text: 'Logistics Dispatched', desc: 'Dengue NS1 Kits dispatched to CHC Bisrakh.', time: '3h ago' }
];

const dengueBarolaRec = dummyMedicines.find(m => m.facilityId === 'phc_barola' && m.name.includes('Dengue'));
const dengueBadalpurRec = dummyMedicines.find(m => m.facilityId === 'phc_badalpur' && m.name.includes('Dengue'));

// Recommendations generated by AI
function buildInitialRecommendations(): AIRecommendation[] {
  return [
    {
      id: 'rec1',
      title: 'Redistribute Dengue Kits',
      sourceFacility: 'phc_barola',
      targetFacility: 'phc_badalpur',
      item: 'Dengue NS1 Antigen Test Kit',
      quantity: 50,
      confidence: 0.94,
      reasoning: `Critical shortage at destination.`,
      timestamp: new Date().toISOString(),
    },
    {
      id: 'rec2',
      title: 'Emergency Paracetamol Dispatch',
      sourceFacility: 'chc_bisrakh',
      targetFacility: 'phc_badalpur',
      item: 'Paracetamol 650mg',
      quantity: 200,
      confidence: 0.98,
      reasoning: `Surplus available for dispatch.`,
      timestamp: new Date().toISOString(),
    },
    {
      id: 'rec3',
      title: 'IV Fluids Reallocation',
      sourceFacility: 'chc_dadri',
      targetFacility: 'chc_bhangel',
      item: 'IV Fluids (NS)',
      quantity: 100,
      confidence: 0.89,
      reasoning: `High demand at target.`,
      timestamp: new Date().toISOString(),
    },
    {
      id: 'rec4',
      title: 'Amoxicillin Transfer',
      sourceFacility: 'uphc_surajpur',
      targetFacility: 'chc_dadri',
      item: 'Amoxicillin 250mg',
      quantity: 150,
      confidence: 0.91,
      reasoning: `Preventive transfer highly recommended.`,
      timestamp: new Date().toISOString(),
    },
    {
      id: 'rec5',
      title: 'Azithromycin Re-stocking',
      sourceFacility: 'chc_bisrakh',
      targetFacility: 'uphc_harola',
      item: 'Azithromycin 500mg',
      quantity: 100,
      confidence: 0.85,
      reasoning: `Urgent stock redistribution needed.`,
      timestamp: new Date().toISOString(),
    }
  ];
}

export let localRecommendations: AIRecommendation[] = buildInitialRecommendations();

// Active transfers (approved recommendations)
export interface TransferOrder {
  id: string;
  recommendationId?: string;
  sourceFacilityId: string;
  targetFacilityId: string;
  medicineId: string;
  medicineName: string;
  quantity: number;
  status: 'PENDING' | 'EN_ROUTE' | 'DELIVERED';
  timestamp: string;
}

function buildInitialTransfers(): TransferOrder[] {
  return [
    {
      id: 'SHP-1234',
      sourceFacilityId: 'phc_barola',
      targetFacilityId: 'phc_badalpur',
      medicineId: 'm2',
      medicineName: 'Dengue NS1 Antigen Test Kit',
      quantity: 50,
      status: 'EN_ROUTE',
      timestamp: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      id: 'SHP-5678',
      sourceFacilityId: 'chc_bisrakh',
      targetFacilityId: 'phc_mandi',
      medicineId: 'm1',
      medicineName: 'Paracetamol 650mg',
      quantity: 200,
      status: 'PENDING',
      timestamp: new Date(Date.now() - 1800000).toISOString(),
    },
    {
      id: 'SHP-9012',
      sourceFacilityId: 'uphc_surajpur',
      targetFacilityId: 'chc_dadri',
      medicineId: 'm5',
      medicineName: 'Amoxicillin 250mg',
      quantity: 150,
      status: 'DELIVERED',
      timestamp: new Date(Date.now() - 86400000).toISOString(),
    }
  ];
}

export let localTransfers: TransferOrder[] = buildInitialTransfers();
// AsyncStorage Persistance Logic
export const hydrateLocalDb = async () => {
  try {
    const keys = ['localPHCs', 'localAttendance', 'localMedicines', 'localAlerts', 'localNotifications', 'localReports', 'localTransfers', 'localRecommendations', 'localTasks'];
    const results = await AsyncStorage.multiGet(keys);
    
    results.forEach(([key, value]) => {
      if (value) {
        const parsed = JSON.parse(value);
        if (key === 'localPHCs') localPHCs = parsed;
        if (key === 'localAttendance') localAttendance = parsed;
        if (key === 'localMedicines') localMedicines = parsed;
        if (key === 'localAlerts') localAlerts = parsed;
        if (key === 'localNotifications') localNotifications = parsed;
        if (key === 'localReports') localReports = parsed;
        if (key === 'localTransfers') localTransfers = parsed;
        if (key === 'localRecommendations') localRecommendations = parsed;
        if (key === 'localTasks') localTasks = parsed;
      }
    });
  } catch (e) {
    console.error('Failed to hydrate local DB', e);
  }
};

const saveState = async (key: string, value: any) => {
  try {
    await AsyncStorage.setItem(key, JSON.stringify(value));
  } catch (e) {
    console.error('Error saving state', e);
  }
};

export const clearLocalDb = async () => {
  try {
    const keys = ['localPHCs', 'localAttendance', 'localMedicines', 'localAlerts', 'localNotifications', 'localReports', 'localTransfers', 'localRecommendations', 'localTasks'];
    await AsyncStorage.multiRemove(keys);

    localPHCs = JSON.parse(JSON.stringify(dummyPHCs));
    localAttendance = JSON.parse(JSON.stringify(dummyAttendance));
    localMedicines = JSON.parse(JSON.stringify(dummyMedicines));
    localAlerts = JSON.parse(JSON.stringify(dummyAlerts));
    localNotifications = JSON.parse(JSON.stringify(dummyNotifications));
    localReports = JSON.parse(JSON.stringify(dummyReports));
    localDistrict = { ...dummyDistrict };
    localLogistics = JSON.parse(JSON.stringify(dummyLogistics));
    localDiseaseTrends = JSON.parse(JSON.stringify(dummyDiseaseTrends));
    localTasks = JSON.parse(JSON.stringify(dummyTasks));
    localRecommendations = buildInitialRecommendations();
    localTransfers = buildInitialTransfers();
  } catch (e) {
    console.error('Failed to clear local DB', e);
  }
};

// Helper functions to update state
export const updateLocalPHC = (updated: PHC) => {
  localPHCs = localPHCs.map((p) => (p.id === updated.id ? updated : p));
  saveState('localPHCs', localPHCs);
};

export const addLocalAttendance = (record: AttendanceRecord) => {
  localAttendance.push(record);
  saveState('localAttendance', localAttendance);
};

export const updateLocalMedicine = (updated: MedicineStock) => {
  localMedicines = localMedicines.map((m) => (m.id === updated.id ? updated : m));
  saveState('localMedicines', localMedicines);
};

export const addLocalMedicine = (newItem: MedicineStock) => {
  localMedicines = [newItem, ...localMedicines];
  saveState('localMedicines', localMedicines);
};

export const updateLocalTask = (updated: TaskItem) => {
  localTasks = localTasks.map((t) => (t.id === updated.id ? updated : t));
  saveState('localTasks', localTasks);
};

export const updateLocalAlert = (updated: AlertItem) => {
  localAlerts = localAlerts.map((a) => (a.id === updated.id ? updated : a));
  saveState('localAlerts', localAlerts);
};

export const addLocalNotification = (notif: NotificationItem) => {
  localNotifications.unshift(notif);
  saveState('localNotifications', localNotifications);
};

export const markAllLocalNotificationsRead = () => {
  localNotifications = localNotifications.map((n) => ({ ...n, read: true }));
  saveState('localNotifications', localNotifications);
};

export const clearLocalNotifications = () => {
  localNotifications = [];
  saveState('localNotifications', localNotifications);
};

export const addLocalTransfer = (transfer: TransferOrder) => {
  localTransfers.push(transfer);
  saveState('localTransfers', localTransfers);
};

export const updateLocalTransferStatus = (id: string, status: 'PENDING' | 'EN_ROUTE' | 'DELIVERED') => {
  localTransfers = localTransfers.map((t) => (t.id === id ? { ...t, status } : t));
  saveState('localTransfers', localTransfers);
};

export const removeLocalRecommendation = (id: string) => {
  localRecommendations = localRecommendations.filter((r) => r.id !== id);
  saveState('localRecommendations', localRecommendations);
};
