import { AlertItem } from '@/shared/types/alert';


export const dummyAlerts: AlertItem[] = [
  {
    id: 'a1',
    title: 'Dengue Surge Warning',
    titleHi: 'डेंगू वृद्धि चेतावनी',
    type: 'OUTBREAK',
    priority: 'CRITICAL',
    facilityId: 'phc_badalpur',
    facilityName: 'PHC Badalpur',
    description: 'Dengue cases have increased by 150% in the last 7 days.',
    descriptionHi: 'पिछले 7 दिनों में डेंगू के मामले 150% बढ़ गए हैं।',
    timestamp: '2026-06-29T10:00:00Z',
    resolved: false,
  },
  {
    id: 'a2',
    title: 'Malaria Cluster Detected',
    titleHi: 'मलेरिया क्लस्टर का पता चला',
    type: 'OUTBREAK',
    priority: 'HIGH',
    facilityId: 'phc_barola',
    facilityName: 'PHC Barola',
    description: 'A new cluster of 15 Malaria cases detected in Sector 49.',
    descriptionHi: 'सेक्टर 49 में 15 मलेरिया मामलों का नया क्लस्टर मिला है।',
    timestamp: '2026-06-29T11:00:00Z',
    resolved: false,
  },
  {
    id: 'a3',
    title: 'Typhoid Warning',
    titleHi: 'टाइफाइड चेतावनी',
    type: 'OUTBREAK',
    priority: 'MEDIUM',
    facilityId: 'chc_bhangel',
    facilityName: 'CHC Bhangel',
    description: 'Increasing reports of water-borne Typhoid cases in Bhangel village.',
    descriptionHi: 'भंगेल गांव में जलजनित टाइफाइड के मामलों की रिपोर्ट बढ़ रही है।',
    timestamp: '2026-06-29T12:30:00Z',
    resolved: false,
  },
  {
    id: 'a4',
    title: 'Viral Fever Outbreak',
    titleHi: 'वायरल बुखार प्रकोप',
    type: 'OUTBREAK',
    priority: 'CRITICAL',
    facilityId: 'chc_dadri',
    facilityName: 'CHC Dadri',
    description: 'Over 200 pediatric viral fever cases reported in 3 days.',
    descriptionHi: '3 दिनों में 200 से अधिक बाल चिकित्सा वायरल बुखार के मामले सामने आए हैं।',
    timestamp: '2026-06-29T14:15:00Z',
    resolved: false,
  },
  {
    id: 'a5',
    title: 'Acute Diarrheal Disease Warning',
    titleHi: 'तीव्र अतिसार रोग चेतावनी',
    type: 'OUTBREAK',
    priority: 'HIGH',
    facilityId: 'uphc_surajpur',
    facilityName: 'UPHC Surajpur',
    description: 'Surge in ADD cases traced to contaminated local water supply.',
    descriptionHi: 'ADD मामलों में वृद्धि का कारण दूषित स्थानीय जल आपूर्ति है।',
    timestamp: '2026-06-29T15:45:00Z',
    resolved: false,
  },
  {
    id: 'a6',
    title: 'Paracetamol Shortage',
    titleHi: 'पैरासिटामोल की कमी',
    type: 'SHORTAGE',
    priority: 'CRITICAL',
    facilityId: 'phc_badalpur',
    facilityName: 'PHC Badalpur',
    description: 'Paracetamol stock is below critical reserve.',
    descriptionHi: 'पैरासिटामोल का स्टॉक महत्वपूर्ण रिज़र्व से नीचे है।',
    timestamp: '2026-06-29T08:30:00Z',
    resolved: false,
  },
  {
    id: 'a7',
    title: 'Dengue NS1 Kit Shortage',
    titleHi: 'डेंगू NS1 किट की कमी',
    type: 'SHORTAGE',
    priority: 'HIGH',
    facilityId: 'phc_barola',
    facilityName: 'PHC Barola',
    description: 'Dengue testing kits critically low due to ongoing outbreak testing.',
    descriptionHi: 'लगातार प्रकोप परीक्षण के कारण डेंगू परीक्षण किट बहुत कम हो गए हैं।',
    timestamp: '2026-06-29T09:15:00Z',
    resolved: false,
  },
  {
    id: 'a8',
    title: 'IV Fluids Shortage',
    titleHi: 'आईवी फ्लूइड्स की कमी',
    type: 'SHORTAGE',
    priority: 'MEDIUM',
    facilityId: 'chc_bhangel',
    facilityName: 'CHC Bhangel',
    description: 'Normal Saline and RL stocks are depleting faster than usual.',
    descriptionHi: 'नॉर्मल सलाइन और RL स्टॉक सामान्य से अधिक तेज़ी से घट रहे हैं।',
    timestamp: '2026-06-29T10:45:00Z',
    resolved: false,
  },
  {
    id: 'a9',
    title: 'Amoxicillin Shortage',
    titleHi: 'अमोक्सिसिलिन की कमी',
    type: 'SHORTAGE',
    priority: 'CRITICAL',
    facilityId: 'chc_dadri',
    facilityName: 'CHC Dadri',
    description: 'Antibiotic reserves exhausted for pediatric ward.',
    descriptionHi: 'बाल रोग वार्ड के लिए एंटीबायोटिक भंडार समाप्त हो गया है।',
    timestamp: '2026-06-29T11:20:00Z',
    resolved: false,
  },
  {
    id: 'a10',
    title: 'Azithromycin Shortage',
    titleHi: 'एज़िथ्रोमाइसिन की कमी',
    type: 'SHORTAGE',
    priority: 'HIGH',
    facilityId: 'uphc_harola',
    facilityName: 'UPHC Harola',
    description: 'Limited stock of broad-spectrum antibiotics remaining.',
    descriptionHi: 'ब्रॉड-स्पेक्ट्रम एंटीबायोटिक्स का सीमित स्टॉक बचा है।',
    timestamp: '2026-06-29T13:00:00Z',
    resolved: false,
  },
];

export default dummyAlerts;
