import { MedicineStock } from '@/shared/types/medicine';

export const dummyMedicines: MedicineStock[] = [
  {
    id: 'm1',
    name: 'Paracetamol 650mg',
    type: 'ANALGESICS',
    currentStock: 127,
    minRequiredStock: 149,
    unit: 'Strips',
    facilityId: 'chc_bisrakh',
  },
  {
    id: 'm2',
    name: 'ORS (Oral Rehydration Salt)',
    type: 'EMERGENCY',
    currentStock: 34,
    minRequiredStock: 369,
    unit: 'Sachets',
    facilityId: 'chc_bisrakh',
  },
  {
    id: 'm3',
    name: 'Amoxicillin 250mg',
    type: 'ANTIBIOTICS',
    currentStock: 156,
    minRequiredStock: 331,
    unit: 'Tablets',
    facilityId: 'chc_bisrakh',
  },
  {
    id: 'm4',
    name: 'Dengue NS1 Kit',
    type: 'EMERGENCY',
    currentStock: 519,
    minRequiredStock: 329,
    unit: 'Kits',
    facilityId: 'chc_bisrakh',
  },
  {
    id: 'm5',
    name: 'IV Fluids',
    type: 'EMERGENCY',
    currentStock: 86,
    minRequiredStock: 166,
    unit: 'Bottles',
    facilityId: 'chc_bisrakh',
  },
  {
    id: 'm6',
    name: 'Paracetamol 650mg',
    type: 'ANALGESICS',
    currentStock: 82,
    minRequiredStock: 301,
    unit: 'Strips',
    facilityId: 'chc_bhangel',
  },
  {
    id: 'm7',
    name: 'ORS (Oral Rehydration Salt)',
    type: 'EMERGENCY',
    currentStock: 485,
    minRequiredStock: 499,
    unit: 'Sachets',
    facilityId: 'chc_bhangel',
  },
  {
    id: 'm8',
    name: 'Amoxicillin 250mg',
    type: 'ANTIBIOTICS',
    currentStock: 450,
    minRequiredStock: 373,
    unit: 'Tablets',
    facilityId: 'chc_bhangel',
  },
  {
    id: 'm9',
    name: 'Dengue NS1 Kit',
    type: 'EMERGENCY',
    currentStock: 102,
    minRequiredStock: 483,
    unit: 'Kits',
    facilityId: 'chc_bhangel',
  },
  {
    id: 'm10',
    name: 'IV Fluids',
    type: 'EMERGENCY',
    currentStock: 473,
    minRequiredStock: 309,
    unit: 'Bottles',
    facilityId: 'chc_bhangel',
  },
  {
    id: 'm11',
    name: 'Paracetamol 650mg',
    type: 'ANALGESICS',
    currentStock: 103,
    minRequiredStock: 337,
    unit: 'Strips',
    facilityId: 'phc_barola',
  },
  {
    id: 'm12',
    name: 'ORS (Oral Rehydration Salt)',
    type: 'EMERGENCY',
    currentStock: 35,
    minRequiredStock: 306,
    unit: 'Sachets',
    facilityId: 'phc_barola',
  },
  {
    id: 'm13',
    name: 'Amoxicillin 250mg',
    type: 'ANTIBIOTICS',
    currentStock: 230,
    minRequiredStock: 423,
    unit: 'Tablets',
    facilityId: 'phc_barola',
  },
  {
    id: 'm14',
    name: 'Dengue NS1 Kit',
    type: 'EMERGENCY',
    currentStock: 67,
    minRequiredStock: 312,
    unit: 'Kits',
    facilityId: 'phc_barola',
  },
  {
    id: 'm15',
    name: 'IV Fluids',
    type: 'EMERGENCY',
    currentStock: 165,
    minRequiredStock: 133,
    unit: 'Bottles',
    facilityId: 'phc_barola',
  },
  {
    id: 'm16',
    name: 'Paracetamol 650mg',
    type: 'ANALGESICS',
    currentStock: 283,
    minRequiredStock: 188,
    unit: 'Strips',
    facilityId: 'uphc_surajpur',
  },
  {
    id: 'm17',
    name: 'ORS (Oral Rehydration Salt)',
    type: 'EMERGENCY',
    currentStock: 16,
    minRequiredStock: 241,
    unit: 'Sachets',
    facilityId: 'uphc_surajpur',
  },
  {
    id: 'm18',
    name: 'Amoxicillin 250mg',
    type: 'ANTIBIOTICS',
    currentStock: 499,
    minRequiredStock: 516,
    unit: 'Tablets',
    facilityId: 'uphc_surajpur',
  },
  {
    id: 'm19',
    name: 'Dengue NS1 Kit',
    type: 'EMERGENCY',
    currentStock: 75,
    minRequiredStock: 439,
    unit: 'Kits',
    facilityId: 'uphc_surajpur',
  },
  {
    id: 'm20',
    name: 'IV Fluids',
    type: 'EMERGENCY',
    currentStock: 321,
    minRequiredStock: 194,
    unit: 'Bottles',
    facilityId: 'uphc_surajpur',
  },
  {
    id: 'm21',
    name: 'Paracetamol 650mg',
    type: 'ANALGESICS',
    currentStock: 32,
    minRequiredStock: 207,
    unit: 'Strips',
    facilityId: 'chc_dadri',
  },
  {
    id: 'm22',
    name: 'ORS (Oral Rehydration Salt)',
    type: 'EMERGENCY',
    currentStock: 81,
    minRequiredStock: 582,
    unit: 'Sachets',
    facilityId: 'chc_dadri',
  },
  {
    id: 'm23',
    name: 'Amoxicillin 250mg',
    type: 'ANTIBIOTICS',
    currentStock: 51,
    minRequiredStock: 107,
    unit: 'Tablets',
    facilityId: 'chc_dadri',
  },
  {
    id: 'm24',
    name: 'Dengue NS1 Kit',
    type: 'EMERGENCY',
    currentStock: 118,
    minRequiredStock: 251,
    unit: 'Kits',
    facilityId: 'chc_dadri',
  },
  {
    id: 'm25',
    name: 'IV Fluids',
    type: 'EMERGENCY',
    currentStock: 279,
    minRequiredStock: 387,
    unit: 'Bottles',
    facilityId: 'chc_dadri',
  },
  {
    id: 'm26',
    name: 'Paracetamol 650mg',
    type: 'ANALGESICS',
    currentStock: 89,
    minRequiredStock: 221,
    unit: 'Strips',
    facilityId: 'phc_badalpur',
  },
  {
    id: 'm27',
    name: 'ORS (Oral Rehydration Salt)',
    type: 'EMERGENCY',
    currentStock: 341,
    minRequiredStock: 321,
    unit: 'Sachets',
    facilityId: 'phc_badalpur',
  },
  {
    id: 'm28',
    name: 'Amoxicillin 250mg',
    type: 'ANTIBIOTICS',
    currentStock: 507,
    minRequiredStock: 475,
    unit: 'Tablets',
    facilityId: 'phc_badalpur',
  },
  {
    id: 'm29',
    name: 'Dengue NS1 Kit',
    type: 'EMERGENCY',
    currentStock: 555,
    minRequiredStock: 574,
    unit: 'Kits',
    facilityId: 'phc_badalpur',
  },
  {
    id: 'm30',
    name: 'IV Fluids',
    type: 'EMERGENCY',
    currentStock: 406,
    minRequiredStock: 250,
    unit: 'Bottles',
    facilityId: 'phc_badalpur',
  },
  {
    id: 'm31',
    name: 'Paracetamol 650mg',
    type: 'ANALGESICS',
    currentStock: 166,
    minRequiredStock: 408,
    unit: 'Strips',
    facilityId: 'uphc_harola',
  },
  {
    id: 'm32',
    name: 'ORS (Oral Rehydration Salt)',
    type: 'EMERGENCY',
    currentStock: 705,
    minRequiredStock: 571,
    unit: 'Sachets',
    facilityId: 'uphc_harola',
  },
  {
    id: 'm33',
    name: 'Amoxicillin 250mg',
    type: 'ANTIBIOTICS',
    currentStock: 217,
    minRequiredStock: 220,
    unit: 'Tablets',
    facilityId: 'uphc_harola',
  },
  {
    id: 'm34',
    name: 'Dengue NS1 Kit',
    type: 'EMERGENCY',
    currentStock: 103,
    minRequiredStock: 215,
    unit: 'Kits',
    facilityId: 'uphc_harola',
  },
  {
    id: 'm35',
    name: 'IV Fluids',
    type: 'EMERGENCY',
    currentStock: 489,
    minRequiredStock: 484,
    unit: 'Bottles',
    facilityId: 'uphc_harola',
  },
  {
    id: 'm36',
    name: 'Paracetamol 650mg',
    type: 'ANALGESICS',
    currentStock: 26,
    minRequiredStock: 170,
    unit: 'Strips',
    facilityId: 'chc_dara_kasna',
  },
  {
    id: 'm37',
    name: 'ORS (Oral Rehydration Salt)',
    type: 'EMERGENCY',
    currentStock: 28,
    minRequiredStock: 141,
    unit: 'Sachets',
    facilityId: 'chc_dara_kasna',
  },
  {
    id: 'm38',
    name: 'Amoxicillin 250mg',
    type: 'ANTIBIOTICS',
    currentStock: 379,
    minRequiredStock: 189,
    unit: 'Tablets',
    facilityId: 'chc_dara_kasna',
  },
  {
    id: 'm39',
    name: 'Dengue NS1 Kit',
    type: 'EMERGENCY',
    currentStock: 371,
    minRequiredStock: 367,
    unit: 'Kits',
    facilityId: 'chc_dara_kasna',
  },
  {
    id: 'm40',
    name: 'IV Fluids',
    type: 'EMERGENCY',
    currentStock: 8,
    minRequiredStock: 490,
    unit: 'Bottles',
    facilityId: 'chc_dara_kasna',
  },
  {
    id: 'm41',
    name: 'Paracetamol 650mg',
    type: 'ANALGESICS',
    currentStock: 56,
    minRequiredStock: 167,
    unit: 'Strips',
    facilityId: 'phc_mandi_shyam_nagar',
  },
  {
    id: 'm42',
    name: 'ORS (Oral Rehydration Salt)',
    type: 'EMERGENCY',
    currentStock: 353,
    minRequiredStock: 315,
    unit: 'Sachets',
    facilityId: 'phc_mandi_shyam_nagar',
  },
  {
    id: 'm43',
    name: 'Amoxicillin 250mg',
    type: 'ANTIBIOTICS',
    currentStock: 96,
    minRequiredStock: 176,
    unit: 'Tablets',
    facilityId: 'phc_mandi_shyam_nagar',
  },
  {
    id: 'm44',
    name: 'Dengue NS1 Kit',
    type: 'EMERGENCY',
    currentStock: 122,
    minRequiredStock: 317,
    unit: 'Kits',
    facilityId: 'phc_mandi_shyam_nagar',
  },
  {
    id: 'm45',
    name: 'IV Fluids',
    type: 'EMERGENCY',
    currentStock: 412,
    minRequiredStock: 238,
    unit: 'Bottles',
    facilityId: 'phc_mandi_shyam_nagar',
  },
  {
    id: 'm46',
    name: 'Paracetamol 650mg',
    type: 'ANALGESICS',
    currentStock: 523,
    minRequiredStock: 500,
    unit: 'Strips',
    facilityId: 'chc_jewar',
  },
  {
    id: 'm47',
    name: 'ORS (Oral Rehydration Salt)',
    type: 'EMERGENCY',
    currentStock: 4,
    minRequiredStock: 164,
    unit: 'Sachets',
    facilityId: 'chc_jewar',
  },
  {
    id: 'm48',
    name: 'Amoxicillin 250mg',
    type: 'ANTIBIOTICS',
    currentStock: 396,
    minRequiredStock: 212,
    unit: 'Tablets',
    facilityId: 'chc_jewar',
  },
  {
    id: 'm49',
    name: 'Dengue NS1 Kit',
    type: 'EMERGENCY',
    currentStock: 340,
    minRequiredStock: 169,
    unit: 'Kits',
    facilityId: 'chc_jewar',
  },
  {
    id: 'm50',
    name: 'IV Fluids',
    type: 'EMERGENCY',
    currentStock: 54,
    minRequiredStock: 250,
    unit: 'Bottles',
    facilityId: 'chc_jewar',
  },
  {
    id: 'm51',
    name: 'Paracetamol 650mg',
    type: 'ANALGESICS',
    currentStock: 269,
    minRequiredStock: 263,
    unit: 'Strips',
    facilityId: 'phc_jahagirpur',
  },
  {
    id: 'm52',
    name: 'ORS (Oral Rehydration Salt)',
    type: 'EMERGENCY',
    currentStock: 50,
    minRequiredStock: 177,
    unit: 'Sachets',
    facilityId: 'phc_jahagirpur',
  },
  {
    id: 'm53',
    name: 'Amoxicillin 250mg',
    type: 'ANTIBIOTICS',
    currentStock: 7,
    minRequiredStock: 301,
    unit: 'Tablets',
    facilityId: 'phc_jahagirpur',
  },
  {
    id: 'm54',
    name: 'Dengue NS1 Kit',
    type: 'EMERGENCY',
    currentStock: 725,
    minRequiredStock: 555,
    unit: 'Kits',
    facilityId: 'phc_jahagirpur',
  },
  {
    id: 'm55',
    name: 'IV Fluids',
    type: 'EMERGENCY',
    currentStock: 17,
    minRequiredStock: 178,
    unit: 'Bottles',
    facilityId: 'phc_jahagirpur',
  },
  {
    id: 'm56',
    name: 'Paracetamol 650mg',
    type: 'ANALGESICS',
    currentStock: 159,
    minRequiredStock: 153,
    unit: 'Strips',
    facilityId: 'phc_rabupura',
  },
  {
    id: 'm57',
    name: 'ORS (Oral Rehydration Salt)',
    type: 'EMERGENCY',
    currentStock: 85,
    minRequiredStock: 113,
    unit: 'Sachets',
    facilityId: 'phc_rabupura',
  },
  {
    id: 'm58',
    name: 'Amoxicillin 250mg',
    type: 'ANTIBIOTICS',
    currentStock: 112,
    minRequiredStock: 571,
    unit: 'Tablets',
    facilityId: 'phc_rabupura',
  },
  {
    id: 'm59',
    name: 'Dengue NS1 Kit',
    type: 'EMERGENCY',
    currentStock: 648,
    minRequiredStock: 452,
    unit: 'Kits',
    facilityId: 'phc_rabupura',
  },
  {
    id: 'm60',
    name: 'IV Fluids',
    type: 'EMERGENCY',
    currentStock: 563,
    minRequiredStock: 379,
    unit: 'Bottles',
    facilityId: 'phc_rabupura',
  },
  // VACCINES
  { id: 'm61', name: 'Polio Drops', type: 'VACCINE' as any, currentStock: 215, minRequiredStock: 150, unit: 'Vials', facilityId: 'phc_barola' },
  { id: 'v1', name: 'BCG Vaccine', type: 'VACCINE' as any, currentStock: 80, minRequiredStock: 50, unit: 'Vials', facilityId: 'phc_barola' },
  { id: 'v2', name: 'Hepatitis B Vaccine', type: 'VACCINE' as any, currentStock: 120, minRequiredStock: 100, unit: 'Vials', facilityId: 'phc_barola' },
  { id: 'v3', name: 'Pentavalent Vaccine', type: 'VACCINE' as any, currentStock: 45, minRequiredStock: 60, unit: 'Vials', facilityId: 'phc_barola' },
  { id: 'v4', name: 'Rotavirus Vaccine', type: 'VACCINE' as any, currentStock: 200, minRequiredStock: 100, unit: 'Vials', facilityId: 'phc_barola' },
  { id: 'v5', name: 'PCV (Pneumococcal)', type: 'VACCINES', currentStock: 30, minRequiredStock: 50, unit: 'Vials', facilityId: 'phc_barola' },
  { id: 'v6', name: 'fIPV', type: 'VACCINES', currentStock: 150, minRequiredStock: 80, unit: 'Vials', facilityId: 'phc_barola' },
  { id: 'v7', name: 'Measles Rubella (MR)', type: 'VACCINES', currentStock: 90, minRequiredStock: 75, unit: 'Vials', facilityId: 'phc_barola' },
  { id: 'v8', name: 'DPT Booster', type: 'VACCINES', currentStock: 110, minRequiredStock: 90, unit: 'Vials', facilityId: 'phc_barola' },
  { id: 'v9', name: 'Tetanus Toxoid (TT)', type: 'VACCINES', currentStock: 500, minRequiredStock: 200, unit: 'Vials', facilityId: 'phc_barola' },
  { id: 'v10', name: 'Japanese Encephalitis', type: 'VACCINES', currentStock: 40, minRequiredStock: 60, unit: 'Vials', facilityId: 'phc_barola' },
  
  // CONSUMABLES
  { id: 'm62', name: 'Surgical Masks', type: 'CONSUMABLES', currentStock: 1200, minRequiredStock: 500, unit: 'Pieces', facilityId: 'phc_barola' },
  { id: 'c1', name: 'Latex Gloves (Medium)', type: 'CONSUMABLES', currentStock: 800, minRequiredStock: 1000, unit: 'Pairs', facilityId: 'phc_barola' },
  { id: 'c2', name: 'Cotton Rolls (500g)', type: 'CONSUMABLES', currentStock: 45, minRequiredStock: 50, unit: 'Rolls', facilityId: 'phc_barola' },
  { id: 'c3', name: 'Bandages (4 inch)', type: 'CONSUMABLES', currentStock: 300, minRequiredStock: 200, unit: 'Rolls', facilityId: 'phc_barola' },
  { id: 'c4', name: 'Syringes (5ml)', type: 'CONSUMABLES', currentStock: 1500, minRequiredStock: 1000, unit: 'Pieces', facilityId: 'phc_barola' },
  { id: 'c5', name: 'Syringes (10ml)', type: 'CONSUMABLES', currentStock: 850, minRequiredStock: 500, unit: 'Pieces', facilityId: 'phc_barola' },
  { id: 'c6', name: 'IV Cannula (20G)', type: 'CONSUMABLES', currentStock: 120, minRequiredStock: 200, unit: 'Pieces', facilityId: 'phc_barola' },
  { id: 'c7', name: 'Adhesive Tape', type: 'CONSUMABLES', currentStock: 60, minRequiredStock: 40, unit: 'Spools', facilityId: 'phc_barola' },
  { id: 'c8', name: 'Gauze Pads', type: 'CONSUMABLES', currentStock: 2500, minRequiredStock: 1500, unit: 'Pieces', facilityId: 'phc_barola' },
  { id: 'c9', name: 'Hand Sanitizer (500ml)', type: 'CONSUMABLES', currentStock: 25, minRequiredStock: 40, unit: 'Bottles', facilityId: 'phc_barola' },
  { id: 'c10', name: 'Biohazard Bags (Red)', type: 'CONSUMABLES', currentStock: 300, minRequiredStock: 200, unit: 'Bags', facilityId: 'phc_barola' },
  
  // EQUIPMENT
  { id: 'm63', name: 'BP Monitor (Digital)', type: 'EQUIPMENT', currentStock: 12, minRequiredStock: 15, unit: 'Units', facilityId: 'phc_barola' },
  { id: 'e1', name: 'Stethoscope', type: 'EQUIPMENT', currentStock: 18, minRequiredStock: 20, unit: 'Units', facilityId: 'phc_barola' },
  { id: 'e2', name: 'Pulse Oximeter', type: 'EQUIPMENT', currentStock: 8, minRequiredStock: 10, unit: 'Units', facilityId: 'phc_barola' },
  { id: 'e3', name: 'Thermometer (Digital)', type: 'EQUIPMENT', currentStock: 25, minRequiredStock: 15, unit: 'Units', facilityId: 'phc_barola' },
  { id: 'e4', name: 'Weighing Scale (Adult)', type: 'EQUIPMENT', currentStock: 5, minRequiredStock: 5, unit: 'Units', facilityId: 'phc_barola' },
  { id: 'e5', name: 'Weighing Scale (Infant)', type: 'EQUIPMENT', currentStock: 3, minRequiredStock: 3, unit: 'Units', facilityId: 'phc_barola' },
  { id: 'e6', name: 'Fetal Doppler', type: 'EQUIPMENT', currentStock: 2, minRequiredStock: 2, unit: 'Units', facilityId: 'phc_barola' },
  { id: 'e7', name: 'Oxygen Cylinder (B Type)', type: 'EQUIPMENT', currentStock: 4, minRequiredStock: 6, unit: 'Cylinders', facilityId: 'phc_barola' },
  { id: 'e8', name: 'Nebulizer Machine', type: 'EQUIPMENT', currentStock: 6, minRequiredStock: 5, unit: 'Units', facilityId: 'phc_barola' },
  { id: 'e9', name: 'Glucometer', type: 'EQUIPMENT', currentStock: 10, minRequiredStock: 10, unit: 'Units', facilityId: 'phc_barola' },
  { id: 'e10', name: 'ECG Machine (Portable)', type: 'EQUIPMENT', currentStock: 1, minRequiredStock: 1, unit: 'Units', facilityId: 'phc_barola' }
];
