import { PHC } from '@/shared/types/phc';

export const dummyPHCs: PHC[] = [
  // Bisrakh Block
  {
    id: 'chc_bisrakh',
    name: 'CHC Bisrakh',
    nameHi: 'सी.एच.सी. बिसरख',
    block: 'Bisrakh',
    blockHi: 'बिसरख',
    healthScore: 85,
    doctorAvailable: true,
    stockStatus: 'adequate',
    activeAlertsCount: 0,
    bedsTotal: 30,
    bedsOccupied: 12,
    latitude: 28.5865,
    longitude: 77.4430,
    establishedYear: 1995,
    phcCode: 'UP-GBN-BIS01',
    consultRooms: 5,
    ambulances: 2,
    o2Cylinders: 15,
    staffTotal: 18,
    staffPresent: 18,
    moName: 'Dr. S. K. Verma',
    weeklyFootfall: [118, 229, 147, 117, 119, 123, 147]
  },
  {
    id: 'chc_bhangel',
    name: 'CHC Bhangel',
    nameHi: 'सी.एच.सी. भंगेल',
    block: 'Bisrakh',
    blockHi: 'बिसरख',
    healthScore: 78,
    doctorAvailable: true,
    stockStatus: 'warning',
    activeAlertsCount: 1,
    bedsTotal: 20,
    bedsOccupied: 18,
    latitude: 28.5355,
    longitude: 77.3910,
    establishedYear: 2002,
    phcCode: 'UP-GBN-BHA02',
    consultRooms: 3,
    ambulances: 1,
    o2Cylinders: 8,
    staffTotal: 12,
    staffPresent: 11,
    moName: 'Dr. Rajesh Kumar',
    weeklyFootfall: [173, 153, 181, 87, 163, 105, 110]
  },
  {
    id: 'phc_barola',
    name: 'PHC Barola',
    nameHi: 'पी.एच.सी. बरौला',
    block: 'Bisrakh',
    blockHi: 'बिसरख',
    healthScore: 65,
    doctorAvailable: true,
    stockStatus: 'critical',
    activeAlertsCount: 3,
    bedsTotal: 10,
    bedsOccupied: 9,
    latitude: 28.5630,
    longitude: 77.3698,
    establishedYear: 2012,
    phcCode: 'UP-GBN-BAR03',
    consultRooms: 2,
    ambulances: 1,
    o2Cylinders: 4,
    staffTotal: 8,
    staffPresent: 6,
    moName: 'Dr. Anita Singh',
    weeklyFootfall: [206, 198, 115, 238, 146, 233, 213]
  },
  {
    id: 'uphc_surajpur',
    name: 'UPHC Surajpur',
    nameHi: 'यू.पी.एच.सी. सूरजपुर',
    block: 'Bisrakh',
    blockHi: 'बिसरख',
    healthScore: 92,
    doctorAvailable: true,
    stockStatus: 'adequate',
    activeAlertsCount: 0,
    bedsTotal: 5,
    bedsOccupied: 1,
    latitude: 28.5245,
    longitude: 77.4812,
    establishedYear: 2018,
    phcCode: 'UP-GBN-SUR04',
    consultRooms: 2,
    ambulances: 0,
    o2Cylinders: 5,
    staffTotal: 6,
    staffPresent: 6,
    moName: 'Dr. Prakash Dev',
    weeklyFootfall: [238, 66, 244, 90, 182, 132, 118]
  },
  // Dadri Block
  {
    id: 'chc_dadri',
    name: 'CHC Dadri',
    nameHi: 'सी.एच.सी. दादरी',
    block: 'Dadri',
    blockHi: 'दादरी',
    healthScore: 74,
    doctorAvailable: true,
    stockStatus: 'adequate',
    activeAlertsCount: 0,
    bedsTotal: 25,
    bedsOccupied: 10,
    latitude: 28.5555,
    longitude: 77.5532,
    establishedYear: 1988,
    phcCode: 'UP-GBN-DAD01',
    consultRooms: 4,
    ambulances: 2,
    o2Cylinders: 20,
    staffTotal: 15,
    staffPresent: 14,
    moName: 'Dr. H. M. Joshi',
    weeklyFootfall: [244, 73, 165, 189, 221, 189, 209]
  },
  {
    id: 'phc_badalpur',
    name: 'PHC Badalpur',
    nameHi: 'पी.एच.सी. बादलपुर',
    block: 'Dadri',
    blockHi: 'दादरी',
    healthScore: 58,
    doctorAvailable: false,
    stockStatus: 'warning',
    activeAlertsCount: 2,
    bedsTotal: 8,
    bedsOccupied: 4,
    latitude: 28.6015,
    longitude: 77.5115,
    establishedYear: 2005,
    phcCode: 'UP-GBN-BAD02',
    consultRooms: 1,
    ambulances: 1,
    o2Cylinders: 2,
    staffTotal: 5,
    staffPresent: 3,
    moName: 'Dr. M. S. Ansari',
    weeklyFootfall: [77, 228, 166, 72, 118, 249, 193]
  },
  {
    id: 'uphc_harola',
    name: 'UPHC Harola',
    nameHi: 'यू.पी.एच.सी. हरौला',
    block: 'Dadri',
    blockHi: 'दादरी',
    healthScore: 81,
    doctorAvailable: true,
    stockStatus: 'adequate',
    activeAlertsCount: 0,
    bedsTotal: 4,
    bedsOccupied: 2,
    latitude: 28.5830,
    longitude: 77.3200,
    establishedYear: 2015,
    phcCode: 'UP-GBN-HAR03',
    consultRooms: 2,
    ambulances: 0,
    o2Cylinders: 3,
    staffTotal: 6,
    staffPresent: 6,
    moName: 'Dr. Vinod Sharma',
    weeklyFootfall: [207, 223, 239, 106, 214, 137, 233]
  },
  // Dankaur Block
  {
    id: 'chc_dara_kasna',
    name: 'CHC Dara Kasna',
    nameHi: 'सी.एच.सी. दारा कासना',
    block: 'Dankaur',
    blockHi: 'दनकौर',
    healthScore: 88,
    doctorAvailable: true,
    stockStatus: 'adequate',
    activeAlertsCount: 0,
    bedsTotal: 20,
    bedsOccupied: 5,
    latitude: 28.4312,
    longitude: 77.5320,
    establishedYear: 2001,
    phcCode: 'UP-GBN-DAR01',
    consultRooms: 3,
    ambulances: 1,
    o2Cylinders: 10,
    staffTotal: 10,
    staffPresent: 10,
    moName: 'Dr. Sunil Patel',
    weeklyFootfall: [74, 87, 243, 78, 240, 249, 64]
  },
  {
    id: 'phc_mandi_shyam_nagar',
    name: 'PHC Mandi Shyam Nagar',
    nameHi: 'पी.एच.सी. मंडी श्याम नगर',
    block: 'Dankaur',
    blockHi: 'दनकौर',
    healthScore: 45,
    doctorAvailable: false,
    stockStatus: 'critical',
    activeAlertsCount: 4,
    bedsTotal: 6,
    bedsOccupied: 6,
    latitude: 28.3750,
    longitude: 77.5510,
    establishedYear: 2010,
    phcCode: 'UP-GBN-MAN02',
    consultRooms: 1,
    ambulances: 0,
    o2Cylinders: 1,
    staffTotal: 4,
    staffPresent: 2,
    moName: 'Dr. Arun Pandey',
    weeklyFootfall: [165, 229, 116, 95, 58, 244, 141]
  },
  // Jewar Block
  {
    id: 'chc_jewar',
    name: 'CHC Jewar',
    nameHi: 'सी.एच.सी. जेवर',
    block: 'Jewar',
    blockHi: 'जेवर',
    healthScore: 70,
    doctorAvailable: true,
    stockStatus: 'warning',
    activeAlertsCount: 1,
    bedsTotal: 30,
    bedsOccupied: 22,
    latitude: 28.1321,
    longitude: 77.5643,
    establishedYear: 1990,
    phcCode: 'UP-GBN-JEW01',
    consultRooms: 4,
    ambulances: 2,
    o2Cylinders: 12,
    staffTotal: 16,
    staffPresent: 14,
    moName: 'Dr. Neha Gupta',
    weeklyFootfall: [176, 195, 231, 232, 240, 225, 233]
  },
  {
    id: 'phc_jahagirpur',
    name: 'PHC Jahagirpur',
    nameHi: 'पी.एच.सी. जहांगीरपुर',
    block: 'Jewar',
    blockHi: 'जेवर',
    healthScore: 95,
    doctorAvailable: true,
    stockStatus: 'adequate',
    activeAlertsCount: 0,
    bedsTotal: 8,
    bedsOccupied: 2,
    latitude: 28.2100,
    longitude: 77.6210,
    establishedYear: 2014,
    phcCode: 'UP-GBN-JAH02',
    consultRooms: 2,
    ambulances: 1,
    o2Cylinders: 5,
    staffTotal: 7,
    staffPresent: 7,
    moName: 'Dr. Vivek Tiwari',
    weeklyFootfall: [138, 57, 169, 71, 92, 75, 239]
  },
  {
    id: 'phc_rabupura',
    name: 'PHC Rabupura',
    nameHi: 'पी.एच.सी. रबुपुरा',
    block: 'Jewar',
    blockHi: 'जेवर',
    healthScore: 61,
    doctorAvailable: true,
    stockStatus: 'warning',
    activeAlertsCount: 2,
    bedsTotal: 10,
    bedsOccupied: 8,
    latitude: 28.2510,
    longitude: 77.6010,
    establishedYear: 2008,
    phcCode: 'UP-GBN-RAB03',
    consultRooms: 1,
    ambulances: 1,
    o2Cylinders: 3,
    staffTotal: 5,
    staffPresent: 4,
    moName: 'Dr. Alok Nath',
    weeklyFootfall: [147, 69, 139, 57, 206, 107, 66]
  }
];

export default dummyPHCs;
